spring:
  application:
    name: chaeking
  profiles:
    active: prod
  config:
    import:
      - chaeking.yml
      - vault://secret/chaeking
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://applebox.xyz:3306/book?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&tinyInt1isBit=false
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
#      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-book
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        default_batch_fetch_size: 500
    open-in-view: false
    show-sql: true

  devtools:
    add-properties: false

  cloud:
    vault:
      host: vault.chaeking.com
      scheme: https
      port: 443
      token: "hvs.CAESIO4DEGw52eKb-ke_DTYZ0JAwJaH6lGqpatVTwNwbN6K2Gh4KHGh2cy5aWjBjaTlBckpGRHY3SEJjVVE0cEhVTG4"
      authentication: token
      kv:
        enabled: true
        default-context: chaeking

  mail:
    host: smtp.daum.net
    port: 465
    username: coco.2222
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

server:
  port: 8080
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: logs
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %{X-Forwarded-For}i(%h) %l %u \"%r\" %s %b"
    remoteip:
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
    syntax-highlight:
      theme: nord
  paths-to-match:
    - /v1/**

logging:
  file:
    name: logs/check.log
  exception-conversion-word: '%wEx'
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%-5p}){green} %clr([%22thread]){magenta} %clr(%-40.40logger{39}){cyan} %clr(: %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}){faint}'
  level:
    web: debug
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}-%i.log
      max-history: 10
